---

- name: Network Getting Started First Playbook Extended
  gather_facts: false
  hosts: jenkins
  become: yes
  become_user: root
  tasks:

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

    - name: Download Jenkins Repo
      get_url:
        url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'

    - name: yum-clean-metadata
      command: yum clean metadata
      args:
        warn: no

    - name: Create java vars
      copy:
        dest: "/etc/profile.d/java.sh"
        content: |
          export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which javac)))))
          export PATH=$PATH:$JAVA_HOME/bin
          export JRE_HOME=/usr/lib/jvm/jre
          export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar

    - name: Install Java 11 and Jenkins
      yum:
        name: "{{packages}}"
        state: latest
      vars:
        packages:
        - java-11-openjdk-devel
        - jenkins
      become: yes
      become_user: root
