---

- name: Upgrade and add required base packages
  gather_facts: false
  hosts: web_servers
  become: yes
  become_user: root
  tasks:

    - name: upgrade all packages
      apt:
        update_cache: yes
        upgrade: dist
      become: yes
      become_user: root
      
    - name: Reboot box if kernel/libs updated and requested by the system
      reboot:
        post_reboot_delay: 120 
   
    - name: Verify new update
      command: uname -mrs
      register: uname_result
      
    - name: Display new kernel version
      debug:
        var: uname_result.stdout_lines
